const menu = {
    list() {
        return [
    {
        "backMenu":[
        ],
        "frontMenu":[
        ],
        "hasBackLogin":"是",
        "hasBackRegister":"否",
        "hasFrontLogin":"否",
        "hasFrontRegister":"否",
        "roleName":"管理员",
        "tableName":"users"
    },
    {
        "backMenu":[
			{
                "child":[
                    {
						"appFrontIcon":"cuIcon-form",
                        "buttons":[
                            "查看",
                        ],
                        "menu":"车次信息",
                        "menuJump":"列表",
                        "tableName":"checi"
                    }
                ],
                "menu":"车次信息"
            }
            ,
            {
                "child":[
                    {
						"appFrontIcon":"cuIcon-favor",
                        "buttons":[
                            "查看",
                            "删除"
                        ],
                        "menu":"车次收藏",
                        "menuJump":"列表",
                        "tableName":"checiCollection"
                    }
                ],
                "menu":"车次收藏"
            }
            ,
            {
                "child":[
                    {
						"appFrontIcon":"cuIcon-evaluate",
                        "buttons":[
                            "查看",
                            "删除"
                        ],
                        "menu":"车次评价",
                        "menuJump":"列表",
                        "tableName":"checiCommentback"
                    }
                ],
                "menu":"车次评价"
            }
            ,
            {
                "child":[
                    {
						"appFrontIcon":"cuIcon-order",
                        "buttons":[
                            "查看",
                            "删除"
                        ],
                        "menu":"购票订单",
                        "menuJump":"列表",
                        "tableName":"checiOrder"
                    }
                ],
                "menu":"购票订单"
            }
            ,
            {
                "child":[
                    {
						"appFrontIcon":"cuIcon-activity",
                        "buttons":[
                            "查看"
                        ],
                        "menu":"通知公告",
                        "menuJump":"列表",
                        "tableName":"news"
                    }
                ],
                "menu":"通知公告"
            }
        ],
        "frontMenu":[
        ],
        "hasBackLogin":"是",
        "hasBackRegister":"否",
        "hasFrontLogin":"是",
        "hasFrontRegister":"是",
        "roleName":"用户",
        "tableName":"yonghu"
    }
]

	}
}
export default menu;
